### ISSUE TITLE
Delete Messages after User Ban

### ISSUE THREAD

**Issue by niceprogramming** [ILiedAboutCake/Bernard#6]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

User is banned on discord but the messages are not deleted.

**Wanted Behavior**
I think the bot should just automatically delete the last days worth of messages for a banned user.
This is already supported by discord and would make for an easy fix. [Ban Documentation](https://discordapp.com/developers/docs/resources/guild#create-guild-ban).

**Comment by ILiedAboutCake** [comment]
Can be done, will add optional flag in ban command to purge last x commands

!ban +purge100 @mention reason

Adding soon(tm)

**Comment by ILiedAboutCake** [comment]
Added !cleanup in https://github.com/ILiedAboutCake/Bernard/commit/1472cdb5c782b5a0ee0c1abd4fceacfc437a47ad 

This was not baked into the ban command, as to report offending messages to Discord it must be done via the deletion -> report to trust and safety team manually via the UI.

User flow should be for best results:

!ban the user
report the message
!cleanup the rest
